# Generated by Django 5.0.1 on 2024-01-23 16:07

import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Secret',
            fields=[
                ('hash', shortuuid.django_fields.ShortUUIDField(alphabet=None, length=16, max_length=16, prefix='secret_', primary_key=True, serialize=False)),
                ('secret_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('remaining_views', models.IntegerField()),
            ],
        ),
    ]
